{
    "name": "Soccer Odds AI Predictions",
    "flow": [
        {
            "id": 4,
            "module": "placeholder:Placeholder",
            "filter": null,
            "metadata": {
                "designer": {
                    "x": -290,
                    "y": 407
                }
            }
        },
        {
            "id": 1,
            "module": "http:MakeRequest",
            "version": 4,
            "parameters": {
                "authenticationType": "noAuth",
                "tlsType": ""
            },
            "mapper": {
                "url": "https://api.the-odds-api.com/v4/sports/soccer_epl/odds/?apiKey=d29bcb40d314689540070106810e6aad&regions=eu&markets=h2h,totals",
                "method": "get",
                "parseResponse": false,
                "stopOnHttpError": true,
                "allowRedirects": true,
                "shareCookies": false,
                "requestCompressedContent": true
            },
            "metadata": {
                "designer": {
                    "x": 10,
                    "y": 407,
                    "name": "Fetch Soccer Odds"
                },
                "restore": {
                    "parameters": {
                        "authenticationType": {
                            "label": "No authenticationUse when no credentials are required for the request."
                        },
                        "tlsType": {
                            "label": "Empty"
                        }
                    },
                    "expect": {
                        "method": {
                            "mode": "chose",
                            "label": "GET"
                        },
                        "headers": {
                            "mode": "chose"
                        },
                        "queryParameters": {
                            "mode": "chose"
                        },
                        "contentType": {
                            "label": "Empty"
                        },
                        "parseResponse": {
                            "mode": "chose"
                        },
                        "stopOnHttpError": {
                            "mode": "chose"
                        },
                        "allowRedirects": {
                            "mode": "chose"
                        },
                        "shareCookies": {
                            "mode": "chose"
                        },
                        "requestCompressedContent": {
                            "mode": "chose"
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "authenticationType",
                        "type": "select",
                        "label": "Authentication type",
                        "required": true,
                        "validate": {
                            "enum": [
                                "noAuth",
                                "apiKey",
                                "basicAuth",
                                "oAuth"
                            ]
                        }
                    },
                    {
                        "name": "tlsType",
                        "type": "select",
                        "label": "Transport layer security (TLS)",
                        "validate": {
                            "enum": [
                                "mTls",
                                "tls"
                            ]
                        }
                    },
                    {
                        "name": "proxyKeychain",
                        "type": "keychain:proxy",
                        "label": "Proxy"
                    }
                ],
                "expect": [
                    {
                        "name": "url",
                        "type": "url",
                        "label": "URL",
                        "required": true
                    },
                    {
                        "name": "method",
                        "type": "select",
                        "label": "Method",
                        "required": true,
                        "validate": {
                            "enum": [
                                "get",
                                "head",
                                "post",
                                "put",
                                "patch",
                                "delete",
                                "options"
                            ]
                        }
                    },
                    {
                        "name": "headers",
                        "type": "array",
                        "label": "Headers",
                        "spec": {
                            "name": "value",
                            "label": "Header
